version: "3.0"

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  yopass:
    image: jhaals/yopass
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - REDIS_URL=redis:6379
    command: "--redis=redis:6379 --port 8080"
